Models/Comida.cs
using System;
using System.Collections.Generic;

#nullable disable

namespace Proyecto1.Models
{
    public partial class Comida
    {
        public Comida()
        {
            SolicitudProductos = new HashSet<SolicitudProducto>();
            VentaComida = new HashSet<VentaComidum>();
        }

        public int IdComida { get; set; }
        public string NomComida { get; set; }
        public string Descripcion { get; set; }
        public byte[] Fotografia { get; set; }
        public decimal? Precio { get; set; }
        public string Estado { get; set; }
        public int? IdComercio { get; set; }

        public virtual AfiliacionComercio IdComercioNavigation { get; set; }
        public virtual ICollection<SolicitudProducto> SolicitudProductos { get; set; }
        public virtual ICollection<VentaComidum> VentaComida { get; set; }
    }
}

Controllers/ComidasController.cs
using Microsoft.AspNetCore.Mvc;

using System;
using System.Collections.Generic;

using System.Linq;
using System.Threading.Tasks;
using Microsoft.EntityFrameworkCore;
using Microsoft.AspNetCore.Mvc.Rendering;
using System.Net;
using System.IO;
using Proyecto1.Models;
using Microsoft.AspNetCore.Http;
using System.Drawing;
using System.Drawing.Imaging;

namespace Proyecto1.Controllers
{
    public class ComidasController : Controller
    {
        private readonly Order2GoContext _context;

        private Comida comidas;

        public ComidasController(Order2GoContext context)
        {

            _context = context;
        }



        public IActionResult Index()
        {

            var listpro = _context.Comidas.Include(d => d.IdComercioNavigation);
            return View(listpro.ToList());



        }

        /* public ActionResult ConvertirImagen(int id)
         {
             Producto imagen = _context.Productos.Where(x => x.IdProducto == id).FirstOrDefault();
             return File(imagen.Fotografia, "image/jpeg");

         }
        */


        public ActionResult getImage(int id)
        {
            Comida comidas = _context.Comidas.Find(id);

            byte[] byteImage = comidas.Fotografia;

            MemoryStream memoryStream = new MemoryStream(byteImage);
#pragma warning disable CA1416 // Validar la compatibilidad de la plataforma
            Image image = Image.FromStream(memoryStream);
#pragma warning restore CA1416 // Validar la compatibilidad de la plataforma


            memoryStream = new MemoryStream();
#pragma warning disable CA1416 // Validar la compatibilidad de la plataforma
            image.Save(memoryStream, ImageFormat.Jpeg);
#pragma warning restore CA1416 // Validar la compatibilidad de la plataforma
            memoryStream.Position = 0;
            return File(memoryStream, "image/jpg");

        }
        public ActionResult Create()
        {
            ViewBag.IdComercio = new SelectList(_context.AfiliacionComercios, "IdComercio", "Nombre");
            return View();
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create(Comida comidas, List<IFormFile> Fotografia)
        {



            foreach (var item in Fotografia)
            {

                if (item.Length > 0)
                {

                    using (var stream = new MemoryStream())
                    {

                        await item.CopyToAsync(stream);
                        comidas.Fotografia = stream.ToArray();
                    }
                }
            }
            _context.Comidas.Add(comidas);
                _context.SaveChanges();
                TempData["mensaje"] = "Comercio agregado correctamente";
                return RedirectToAction("Index");

            

        }




        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Comida comidas = _context.Comidas.Find(id);
            if (comidas == null)
            {
                return HttpNotFound();
            }
            ViewBag.IdComercio = new SelectList(_context.AfiliacionComercios, "IdComercio", "Nombre", comidas.IdComercio);
            return View(comidas);
        }

        private ActionResult HttpNotFound()
        {
            throw new NotImplementedException();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit(Comida comidas, List<IFormFile> Fotografia)
        {

            foreach (var item in Fotografia)
            {

                if (item.Length > 0)
                {

                    using (var stream = new MemoryStream())
                    {

                        await item.CopyToAsync(stream);
                        comidas.Fotografia = stream.ToArray();
                    }
                }
            }

            _context.Entry(comidas).State = EntityState.Modified;
                _context.SaveChanges();
                return RedirectToAction("Index");
            
            ViewBag.IdComercio = new SelectList(_context.AfiliacionComercios, "IdComercio", "Nombre", comidas.IdComercio);
            return View(comidas);
        }















        // GET: DETALLE_COMPRA/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Comida comidas = _context.Comidas.Find(id);
            if (comidas == null)
            {
                return HttpNotFound();
            }
            return View(comidas);
        }


        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Comida comidas = _context.Comidas.Find(id);
            _context.Comidas.Remove(comidas);
            _context.SaveChanges();
            return RedirectToAction("Index");
        }

    }
}

Views/Comidas/Create.cshtml
@model Proyecto1.Models.Comida

@{
    ViewData["Title"] = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}



<h4>Registrar comida</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create" method="post" enctype="multipart/form-data">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="NomComida" class="control-label">Nombre comida</label>
                <input asp-for="NomComida" class="form-control" />
                <span asp-validation-for="NomComida" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Descripcion" class="control-label">Descripción</label>
                <input asp-for="Descripcion" class="form-control" />
                <span asp-validation-for="Descripcion" class="text-danger"></span>
            </div>

            <div class="form-group">
                <label asp-for="Fotografia" class="control-label">Fotografía</label>
                <input type="file" id="files" asp-for="Fotografia" />
                <span asp-validation-for="Fotografia" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Precio" class="control-label">Precio</label>
                <input asp-for="Precio" class="form-control" />
                <span asp-validation-for="Precio" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Estado" class="control-label">Estado</label>
                <input asp-for="Estado" class="form-control" />
                <span asp-validation-for="Estado" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="IdComercio" class="control-label">Comercio</label>
                <select asp-for="IdComercio" class="form-control" asp-items="ViewBag.IdComercio"></select>
            </div>
            <div class="form-group">
                <input type="submit" value="Agregar" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a class="btn btn-primary" asp-action="Index">Regresar</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/Comidas/Delete.cshtml
@model Proyecto1.Models.Comida

@{
    ViewData["Title"] = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}


<h3>Eliminar comida</h3>
<div>
    <h4>Comida</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.NomComida)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.NomComida)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Descripcion)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Descripcion)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Fotografia)
        </dt>
        <dd class = "col-sm-10">
            <img width="100" src="@Url.Action("getImage" ,"Comidas" ,new { id = Model.IdComida })" />
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Precio)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Precio)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Estado)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Estado)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.IdComercioNavigation)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.IdComercioNavigation.IdComercio)
        </dd class>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="IdComida" />
        <input type="submit" value="Eliminar" class="btn btn-danger" /> |
        <a class="btn btn-primary" asp-action="Index">Regresar</a>
    </form>
</div>

Views/Comidas/Edit.cshtml
@model Proyecto1.Models.Comida

@{
    ViewData["Title"] = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}



<h4>Editar comida</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit" method="post" enctype="multipart/form-data">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="IdComida" />
            <div class="form-group">
                <label asp-for="NomComida" class="control-label">Nombre comida</label>
                <input asp-for="NomComida" class="form-control" />
                <span asp-validation-for="NomComida" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Descripcion" class="control-label">Descripción</label>
                <input asp-for="Descripcion" class="form-control" />
                <span asp-validation-for="Descripcion" class="text-danger"></span>
            </div>

            <div class="form-group">

                <div class="col-md-10">
                    <label>Fotografía</label>
                    <br />
                    <img width="100" src="@Url.Action("getImage" ,"Comidas" ,new { id = Model.IdComida })" />
                </div>
                <br />
                <div class="form-group">

                    <input type="file" name="Fotografia" />
                </div>

            </div>


            <div class="form-group">
                <label asp-for="Precio" class="control-label">Precio</label>
                <input asp-for="Precio" class="form-control" />
                <span asp-validation-for="Precio" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Estado" class="control-label">Estado</label>
                <input asp-for="Estado" class="form-control" />
                <span asp-validation-for="Estado" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="IdComercio" class="control-label">Comercio</label>
                <select asp-for="IdComercio" class="form-control" asp-items="ViewBag.IdComercio"></select>
                <span asp-validation-for="IdComercio" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Actualizar" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a class="btn btn-primary" asp-action="Index">Regresar</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/Comidas/Index.cshtml
@model IEnumerable<Proyecto1.Models.Comida>

@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Comidas</h1>

<p>
    <a class="btn btn-primary" asp-action="Create">Nuevo Registro</a>
</p>
<table class="table table-bordered table-striped">
    <thead>
        <tr>
            <th>
                <center>
                    <label>Comida</label>
                </center>
            </th>
            <th>
                <center>
                    <label>Descripción</label>
                </center>
            </th>
            <th>
                <center>
                    <label>Fotografía</label>
                </center>
            </th>
            <th>
                <center>
                    <label>Precio</label>
                </center>
            </th>
            <th>
                <center>
                    <label>Estado</label>
                </center>
            </th>
            <th>
                <center>
                    <label>Comercio a cargo</label>
                </center>
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.NomComida)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Descripcion)
            </td>
            <td>

                <img width="100" src="@Url.Action("getImage" ,"Comidas" ,new { id = item.IdComida })" />
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Precio)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Estado)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.IdComercioNavigation.Nombre)
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.IdComida" class="btn btn-warning" >Editar</a> |
               
                <a asp-action="Delete" asp-route-id="@item.IdComida" class="btn btn-danger">Eliminar</a>
            </td>
        </tr>
}
    </tbody>
</table>